### ISSUE TITLE
Wrong Label or Repeating Field in ORM Stack Template

### ISSUE THREAD

**Issue by chanstev** [oracle-quickstart/oci-landing-zones#18]
There are fields with same label but might refer to different input actually, e.g. "Enable Compartment Delete" is referring to break glass user. Not sure about the others but it's confusing. 

![Screenshot 2023-04-28 at 12 10 39](https://user-images.githubusercontent.com/22254955/235136904-269a3217-b023-4480-b53f-3dae27292f99.png)
![Screenshot 2023-04-28 at 12 30 23](https://user-images.githubusercontent.com/22254955/235136906-e80cf638-706a-49ef-af78-d9dbc2539aa2.png)
![Screenshot 2023-04-28 at 12 30 31](https://user-images.githubusercontent.com/22254955/235136908-1ac01712-c404-466a-b337-129e45aa8d28.png)
![Screenshot 2023-04-28 at 12 30 51](https://user-images.githubusercontent.com/22254955/235136969-c3a3642c-578c-4809-be98-48e9338043c9.png)

**Comment by paulmuah** [comment]
Hey @chanstev we're tracking this issue under LANZ-1560. We will keep you updated with progress.

**Comment by VinayKumar611** [comment]
Hey @chanstev , 

First Issue 
Break Glass User Email and  Enable Compartment Delete variables are independent . Both the variables are mandatory

1) Break Glass User Email           : Provide a valid Email Address 
2) Enable Compartment Delete  : True(Check the Button) or False 

<img width="1037" alt="image" src="https://github.com/oracle-quickstart/oci-landing-zones/assets/2154456/0a053d39-955e-46b3-a88c-414046debb62">


Second Issue , 

Please use the current version 2.1.1 , this issue is not present there.
<img width="1176" alt="image" src="https://github.com/oracle-quickstart/oci-landing-zones/assets/2154456/37fed0ee-c844-49db-8596-3c8ed09c6bfe">

**Comment by VinayKumar611** [comment]
https://github.com/oracle-quickstart/oci-landing-zones/issues/18#issuecomment-1650721321
